create table ASOCIATIE_DE_LOCATARI(
NUME_ASOCIATIE VARCHAR(50) NOT NULL,
ADMINISTRATOR VARCHAR(50) NOT NULL,
ID_LOCATAR INT NOT NULL UNIQUE auto_increment,
NUME_LOCATAR VARCHAR(50) NOT NULL,
PRENUME_LOCATAR VARCHAR(50) NOT NULL,
ADRESA varchar(50) NOT NULL,
NR_LOCUITORI INT NOT NULL,
FACTURA DOUBLE (6,2) NOT NULL,
INDEX_APA INT NOT NULL,
PRIMARY KEY (ID_LOCATAR),
CHECK (NR_LOCUITORI< 7)
);
SELECT * FROM ASOCIATIE_DE_LOCATARI;
SELECT * FROM ASOCIATIE_DE_LOCATARI
WHERE ADRESA  IN ("STR MIRCEA CEL BATRAN NR 18 AP 13 IASI");
SELECT ADMINISTRATOR FROM ASOCIATIE_DE_LOCATARI;
SELECT * FROM ASOCIATIE_DE_LOCATARI;
SELECT NUME_LOCATAR,PRENUME_LOCATAR,FACTURA
FROM ASOCIATIE_DE_LOCATARI
WHERE FACTURA=(SELECT MAX(FACTURA) FROM ASOCIATIE_DE_LOCATARI);
SELECT NUME_LOCATAR,PRENUME_LOCATAR,INDEX_APA
FROM ASOCIATIE_DE_LOCATARI
WHERE INDEX_APA=(SELECT MAX(INDEX_APA) FROM ASOCIATIE_DE_LOCATARI);
ALTER TABLE ASOCIATIE_DE_LOCATARI
ADD LUNA VARCHAR(50);
UPDATE ASOCIATIE_DE_LOCATARI SET LUNA="DECEMBRIE";
SELECT * FROM ASOCIATIE_DE_LOCATARI;
SELECT NUME_LOCATAR,PRENUME_LOCATAR,INDEX_APA,LUNA
FROM ASOCIATIE_DE_LOCATARI
WHERE INDEX_APA=(SELECT MAX(INDEX_APA) FROM ASOCIATIE_DE_LOCATARI);
SELECT NUME_LOCATAR,PRENUME_LOCATAR,INDEX_APA,FACTURA,LUNA
FROM ASOCIATIE_DE_LOCATARI
WHERE INDEX_APA=(SELECT MAX(INDEX_APA) FROM ASOCIATIE_DE_LOCATARI)
AND FACTURA=(SELECT MAX(FACTURA) FROM ASOCIATIE_DE_LOCATARI);